### ISSUE TITLE
Use interface defined in supplied config

### ISSUE THREAD

**Issue by ninewayhandshake** [Daritos/capev2-playbooks#1]
https://github.com/Daritos/capev2-playbooks/blob/815b3b4eab009c25d29337e4206716063e92cf38/roles/capev2/templates/conf/routing.conf.j2#L65

**Comment by Daritos** [comment]
Pushed commit efd5045fe95f5236b453bd6a62a48e5c48bf6b6d which adds variables that allows you to configure the TOR settings for CAPE deployed by the playbook.
Also updated the instructions in README to highlight the newly available variables.
